spring:
  profiles: 
    active: dev  # 激活开发环境配置
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在路径
  type-aliases-package: com.learn.springcloud.api.domain  #所有domain别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml #mapper映射文件

spring:
  profiles:dev #开发环境
  application:
    name: provide-product-config  #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/springcloud_01?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    dbcp2:min-idle: 5       # 数据库连接池的最小维持连接数
    initial-size: 5         # 初始化连接数
    max-total: 5            # 最大连接数
    max-wait-millis: 150    # 等待连接获取的最大超时时间
eureka:
  client:
    registerWithEureka: true  #服务注册开关
    fetch-registry: true  #服务发现开关
    serviceUrl:  #客户端（服务提供者）注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}-hystrix #指定实例ID。就不会显示主机名称了
    preferIPAddress: true  #让访问路径显示IP地址

---

server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在路径
  type-aliases-package: com.learn.springcloud.api.domain  #所有domain别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml #mapper映射文件

spring:
  profiles:prod #生产环境
  application:
    name: provide-product-config  #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/springcloud_02?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    dbcp2:min-idle: 5       # 数据库连接池的最小维持连接数
    initial-size: 5         # 初始化连接数
    max-total: 5            # 最大连接数
    max-wait-millis: 150    # 等待连接获取的最大超时时间
eureka:
  client:
    registerWithEureka: true  #服务注册开关
    fetch-registry: true  #服务发现开关
    serviceUrl:  #客户端（服务提供者）注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}-hystrix #指定实例ID。就不会显示主机名称了
    preferIPAddress: true  #让访问路径显示IP地址